spring.application.name=auth-service
server.port=8082

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/app-realm/protocol/openid-connect/certs

keycloak.root.server-url=http://localhost:8080
keycloak.root.client=${KEYCLOAK_ROOT_CLIENT}
keycloak.root.realm=${KEYCLOAK_ROOT_REALM}
keycloak.root.username=${KEYCLOAK_ROOT_USERNAME}
keycloak.root.password=${KEYCLOAK_ROOT_PASSWORD}
keycloak.root.secret=${KEYCLOAK_ROOT_SECRET}

keycloak.manage.server-url=http://localhost:8080
keycloak.manage.client=${KEYCLOAK_MANAGE_CLIENT}
keycloak.manage.realm=${KEYCLOAK_MANAGE_REALM}
keycloak.manage.secret=${KEYCLOAK_MANAGE_SECRET}

keycloak.auth.server-url=http://localhost:8080
keycloak.auth.client=${KEYCLOAK_AUTH_CLIENT}
keycloak.auth.realm=${KEYCLOAK_AUTH_REALM}
keycloak.auth.secret=${KEYCLOAK_AUTH_SECRET}
keycloak.auth.redirect-uri=${KEYCLOAK_AUTH_REDIRECT_URI}
keycloak.auth.state=${KEYCLOAK_AUTH_STATE}

spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT}/${DB_DATABASE}
spring.datasource.username=${APP_USER}
spring.datasource.password=${APP_USER_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
