spring.application.name=auth-service
server.port=8081

keycloak.root.server-url=${KEYCLOAK_ROOT_SERVER_URL}
keycloak.root.client=${KEYCLOAK_ROOT_CLIENT}
keycloak.root.realm=${KEYCLOAK_ROOT_REALM}
keycloak.root.username=${KEYCLOAK_ROOT_USERNAME}
keycloak.root.password=${KEYCLOAK_ROOT_PASSWORD}
keycloak.root.secret=${KEYCLOAK_ROOT_SECRET}

keycloak.manage.server-url=${KEYCLOAK_MANAGE_SERVER_URL}
keycloak.manage.client=${KEYCLOAK_MANAGE_CLIENT}
keycloak.manage.realm=${KEYCLOAK_MANAGE_REALM}
keycloak.manage.secret=${KEYCLOAK_MANAGE_SECRET}

keycloak.auth.server-url=${KEYCLOAK_AUTH_SERVER_URL}
keycloak.auth.client=${KEYCLOAK_AUTH_CLIENT}
keycloak.auth.realm=${KEYCLOAK_AUTH_REALM}
keycloak.auth.secret=${KEYCLOAK_AUTH_SECRET}
keycloak.auth.redirect-uri=${KEYCLOAK_AUTH_REDIRECT_URI}
keycloak.auth.state=${KEYCLOAK_AUTH_STATE}
