spring.application.name=auth-service
server.port=8082
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK_SET_URI}

keycloak.open-id.connect.uri=${KEYCLOAK_OPEN_ID_CONNECT_URI}
user-service.register.uri=${USER_SERVICE_REGISTER_URI}