spring.application.name=auth-service
server.port=8081

keycloak.root.server-url=http://localhost:8080/
keycloak.root.client=admin-cli
keycloak.root.realm=master
keycloak.root.username=admin
keycloak.root.password=admin
keycloak.root.secret=gUxWARNX4QK4bWtrC5JLoi520o1ixrQm

keycloak.manage.server-url=http://localhost:8080/
keycloak.manage.client=app-manage-client
keycloak.manage.realm=app-realm
keycloak.manage.secret=gUxWARNX4QK4bWtrC5JLoi520o1ixrQm
keycloak.use-resource-role-mappings=true

keycloak.auth.server-url=http://localhost:8080/
keycloak.auth.client=app-auth-client
keycloak.auth.realm=app-realm
keycloak.auth.secret=gUxWARNX4QK4bWtrC5JLoi520o1ixrQm
